name: Tests

on: [push, pull_request]

jobs:
  build:

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [3.6]
        platform: [ubuntu-latest]
    
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: CloudFormation lint
      run: |
        python -m pip install --upgrade pip
        python -m pip install cfn-lint
        for y in `find deploy/* -name "*.yaml" -o -name "*.template" -o -name "*.json"`; do echo "============= $y ================" ; cfn-lint --fail-on-warnings $y || ec1=$?; done
        if [ "$ec1" -ne "0" ]; then echo 'ERROR-1'; else echo 'SUCCESS-1'; ec1=0; fi
        echo "Exit Code 1 `echo $ec1`"
        if [ "$ec1" -ne "0" ]; then echo 'ERROR'; ec=1; else echo 'SUCCESS'; ec=0; fi;
        echo "Exit Code Final `echo $ec`"
        exit $ec
    - name: Style check
      run: |
        python -m pip install black
        black --check src
    - name: Type check
      run: |
        python -m pip install mypy
        mypy --ignore-missing-imports src
    - name: Install test dependencies
      run: |
        python -m pip install mxnet==1.6.0 gluonts pytest
    - name: Test with pytest
      run: |
        pytest --pyargs src
